### PR TITLE
Newsweek Bootstrap 4

### PR DESCRIPTION
**Pull request by okikiola11**
# What does this PR do?

- Shows how to use bootstrap 4 classes

#  Description of Task to be completed?

- Shows how to use the nav and navbar tag in bootstrap 4
- Shows how to use the different grid sizes, flex box in bootstrap 4
- Shows how to make the page responsive using bootstrap 4 classes
- Shows how to collapse and display elements using bootstrap 4 classes
- Shows the usage of 2 or 3 web fonts
- Shows the use of different color combination
- Fix stylelint to correct code linting errors
- Fix HTML validator to correct HTML element errors
- Shows the usage of semantic tags in Bootstrap 4

# How should this be manually tested?

- Clone this branch	
- open the index.html file on your browser

# Screenshot 
screenshot

### CODE REVIEW

**Comment by Dandush03** [comment]
# :red_circle: Status: Required Changes :red_circle:
### Hey @okikiola11 :wave: 
## Good attempts on this one :muscle: :+1: 

## Your project looks great! there are some changes to do before submitting another code review :point_down: 

### Page structure @media min-width: 768px

#### 'THE DEBATE' Section
- [ ] Images should resize to look alike the original page
##### Requirements:
Screenshot from 2020-04-03 08-49-42

##### Yours:
Screenshot from 2020-04-03 08-49-31

#### 'IN THE MAGAZINE' Section
- [ ] Firs image is like an advertisement it doesn't contain any text but it's high cover the same height as other images with text
##### Requirements:
Screenshot from 2020-04-03 08-50-23

##### Yours:
Screenshot from 2020-04-03 08-50-03

#### 'EDITORS PICK' Section
- [ ] This section should split in to 2 article per row in this width
##### Requirements:
Screenshot from 2020-04-03 08-50-36

##### Yours:
Screenshot from 2020-04-03 08-50-48

#### 'CATEGORYS NEWS (BUSINESS, WORLD, ETC.)' Section
- [ ] The images of the left section are streching up
##### Requirements:
Screenshot from 2020-04-03 08-51-28

##### Yours:
Screenshot from 2020-04-03 08-51-18

### Implementation details

- [ ] It uses Bootstrap Css classes **everywhere** for styling (for example [Grid layout](https://getbootstrap.com/docs/4.3/layout/overview/) and [Flex](https://getbootstrap.com/docs/4.3/layout/utilities-for-layout/#flexbox-options)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/using_bootstrap/bootstrap_classes_requirement.png) from [Pathwrigth](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540308/))

### Additional Microverse Requirements (Pathwright)

### General

- [ ] Comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

### Section specific

- [ ] Check HTML markup with this [validator](https://validator.w3.org/#validate_by_upload). ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png) from Pathwright)
  > You're receiving a validation error, check it out

- [ ] Make sure that basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
    - no `!import` overusing
    - no inefficient selectors
    - no inline styling

## Kindly address all these changes and submit a new code review

### Happy coding:computer: 

#### Daniel Laloush

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello @okikiola11! 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️

- [ ]  As the last TSE required, 'check HTML markup with this validator. (screenshot from Pathwright)' Consider fixing this error that the validator is complaining about. (link to the
error

- [ ] As the last TSE required, please fix the image on 'the debate' section as the original page:



Original:


- [ ]  As the last TSE required, 'It uses Bootstrap CSS classes everywhere for styling (for example Grid layout and Flex) (screenshot from Pathwrigth)' please add this.

- [ ] As the last TSE required, 'Make sure that basic CSS bad practices are not used (article for support ) (screenshot from Pathwright)' consider no repeating the same rule, for example:

Screenshot from 2020-04-03 17-33-22

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Comment by lekegitrepo** [comment]
### Hi @okikiola11 :+1: 
### You have done a good by implementing most of the required changes mentioned by the previous TSE but you haven't implemented one :point_down: 

**_instead of implementing these rules separately:_**
```
.card-title a:hover {
  text-decoration-color: #f72210;
}
```
```
.txt-font a:hover,
.news-col a:hover,
.state-color a:hover {
  color: #f72210;
  transition: color 0.4s;
  text-decoration: none;
}
```
**_group them together like this:_**

```
.txt-font a:hover,
.news-col a:hover,
.state-color a:hover,
.card-title a:hover {
  color: #f72210;
}
```
you can also add the rules that I removed if you want the same effect on .card-title class
  ```
transition: color 0.4s;
  text-decoration: none; 
```
**_if you have any doubts or questions contact me on slack_**

### Reviewed by: _Temitayo Adeleke_

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
### Status: Require changes

**Comment by uryelah** [comment]
Hello **Okiki Apelehin**, I'm Sarah, your last reviewer for this PR 👩‍🚀  

Great job working on all the previous fixes! Your project looks awesome, you showed a lot of attention to details, and this PR message is in itself quite impressive!

------
## Your project is approved! 🎊 🥅 💛 
### 
**You may close this Pull Request and merge the changes**

----

**Keep being an awesome dev and good luck with your next project!**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Pull request merged**
